# Generated by Django 5.2.9 on 2026-02-24 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique node code (e.g., PARIS_NORD)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the node', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude', max_digits=9)),
                ('capacity', models.IntegerField(default=10, help_text='Number of tracks', validators=[django.core.validators.MinValueValidator(1)])),
                ('node_type', models.CharField(choices=[('STATION', 'Station'), ('JUNCTION', 'Junction'), ('DEPOT', 'Depot')], default='STATION', max_length=20)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for this node', max_length=64)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='core_node_code_d3fce3_idx'), models.Index(fields=['node_type'], name='core_node_node_ty_08dbda_idx'), models.Index(fields=['is_deleted'], name='core_node_is_dele_4aefc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique track code (e.g., T1A)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Track name or description', max_length=255)),
                ('track_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('length_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Track length in meters', max_digits=10, null=True)),
                ('max_speed_kmh', models.IntegerField(default=120, help_text='Maximum speed in km/h', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('BIDIRECTIONAL', 'Bidirectional')], default='BIDIRECTIONAL', max_length=20)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance'), ('CLOSED', 'Closed')], default='OPERATIONAL', max_length=20)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.node')),
            ],
            options={
                'ordering': ['node', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_number', models.CharField(help_text='Unique train identifier', max_length=20, unique=True)),
                ('train_type', models.CharField(choices=[('TGV', 'TGV (High-Speed)'), ('INTERCITE', 'Intercité'), ('TER', 'TER (Regional)'), ('CARGO', 'Cargo'), ('MAINTENANCE', 'Maintenance')], max_length=50)),
                ('operator', models.CharField(help_text='Operating company', max_length=100)),
                ('capacity_passengers', models.IntegerField(blank=True, help_text='Passenger capacity (null for cargo)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('length_meters', models.DecimalField(decimal_places=2, help_text='Train length in meters', max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_speed_kmh', models.IntegerField(help_text='Maximum speed in km/h', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(400)])),
            ],
            options={
                'ordering': ['train_number'],
                'indexes': [models.Index(fields=['train_number'], name='core_train_train_n_eec824_idx'), models.Index(fields=['train_type'], name='core_train_train_t_68f6b5_idx'), models.Index(fields=['operator'], name='core_train_operato_9d45e9_idx'), models.Index(fields=['is_deleted'], name='core_train_is_dele_4b55a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_arrival', models.DateTimeField(db_index=True)),
                ('scheduled_departure', models.DateTimeField(db_index=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay in minutes (negative for early)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.node')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.track')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.train')),
            ],
            options={
                'ordering': ['scheduled_arrival'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('WEATHER', 'Weather'), ('ACCIDENT', 'Accident'), ('SECURITY', 'Security'), ('STRIKE', 'Strike'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.node')),
                ('affected_tracks', models.ManyToManyField(blank=True, related_name='incidents', to='core.track')),
                ('affected_trains', models.ManyToManyField(blank=True, related_name='incidents', to='core.train')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('ARRIVAL', 'Train Arrival'), ('DEPARTURE', 'Train Departure'), ('DELAY', 'Delay'), ('TRACK_CHANGE', 'Track Change'), ('MAINTENANCE', 'Maintenance'), ('ALERT', 'Alert'), ('INCIDENT', 'Incident')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.node')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.track')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.train')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['node', 'status'], name='core_track_node_id_bcf3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['status'], name='core_track_status_385dad_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['code'], name='core_track_code_261dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_deleted'], name='core_track_is_dele_3c41f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('node', 'track_number')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['scheduled_arrival'], name='core_schedu_schedul_11ab4e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['scheduled_departure'], name='core_schedu_schedul_9298d6_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['train', 'scheduled_arrival'], name='core_schedu_train_i_27474f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['node', 'scheduled_arrival'], name='core_schedu_node_id_f59842_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='core_schedu_status_a9432e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_deleted'], name='core_schedu_is_dele_213bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['node', 'status'], name='core_incide_node_id_6ee4be_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['started_at'], name='core_incide_started_625644_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'status'], name='core_incide_severit_7b1dce_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_deleted'], name='core_incide_is_dele_7670de_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp', 'event_type'], name='core_event_timesta_743bad_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['node', 'timestamp'], name='core_event_node_id_625df7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['train', 'timestamp'], name='core_event_train_i_72434b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['severity'], name='core_event_severit_be1262_idx'),
        ),
    ]
