# Generated by Django 5.2.9 on 2026-02-24 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railway_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Scenario name', max_length=255)),
                ('description', models.TextField(help_text='Detailed scenario description')),
                ('scenario_type', models.CharField(choices=[('DELAY', 'Train Delay'), ('CLOSURE', 'Track Closure'), ('CONGESTION', 'Congestion'), ('INCIDENT', 'Incident Response'), ('MAINTENANCE', 'Maintenance Window'), ('CUSTOM', 'Custom Scenario')], max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Scenario configuration parameters (JSON)')),
                ('is_template', models.BooleanField(default=False, help_text='Is this a template scenario?')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
                ('target_node', models.ForeignKey(blank=True, help_text='Primary node affected by scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_scenarios', to='railway_core.node')),
            ],
            options={
                'verbose_name': 'Simulation Scenario',
                'verbose_name_plural': 'Simulation Scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Simulation results and analysis (JSON)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if simulation failed')),
                ('execution_time_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Total execution time', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this simulation run')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='railway_simulation.simulationscenario')),
            ],
            options={
                'verbose_name': 'Simulation Run',
                'verbose_name_plural': 'Simulation Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['scenario_type'], name='railway_sim_scenari_fb958b_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['target_node'], name='railway_sim_target__d6be30_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['is_template'], name='railway_sim_is_temp_d2525c_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['is_deleted'], name='railway_sim_is_dele_27327c_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['scenario', 'started_at'], name='railway_sim_scenari_6ee96f_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['status'], name='railway_sim_status_27a243_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['run_by'], name='railway_sim_run_by__e42e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['started_at'], name='railway_sim_started_32a5cd_idx'),
        ),
    ]
