# Generated by Django 5.2.9 on 2026-02-24 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Model name', max_length=255)),
                ('model_type', models.CharField(choices=[('CONGESTION_PREDICTION', 'Congestion Prediction'), ('ANOMALY_DETECTION', 'Anomaly Detection'), ('RISK_SCORING', 'Risk Scoring'), ('DELAY_PREDICTION', 'Delay Prediction'), ('DEMAND_FORECASTING', 'Demand Forecasting')], max_length=50)),
                ('version', models.CharField(help_text='Model version (e.g., v1.0, v2.1)', max_length=50)),
                ('algorithm', models.CharField(help_text='Algorithm used (e.g., RandomForest, LSTM, IsolationForest)', max_length=100)),
                ('model_path', models.CharField(help_text='Path to model file (local or S3)', max_length=500)),
                ('metrics', models.JSONField(default=dict, help_text='Model performance metrics (JSON)')),
                ('trained_at', models.DateTimeField(help_text='When the model was trained')),
                ('training_duration_seconds', models.IntegerField(blank=True, help_text='Training duration in seconds', null=True)),
                ('training_data_size', models.IntegerField(blank=True, help_text='Number of training samples', null=True)),
                ('training_date_range_start', models.DateTimeField(blank=True, help_text='Start date of training data', null=True)),
                ('training_date_range_end', models.DateTimeField(blank=True, help_text='End date of training data', null=True)),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='Model hyperparameters (JSON)')),
                ('is_active', models.BooleanField(default=False, help_text='Is this the currently active model for its type?')),
                ('description', models.TextField(blank=True, help_text='Model description and notes')),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the prediction was made')),
                ('target_time', models.DateTimeField(db_index=True, help_text='Time period being predicted')),
                ('prediction_value', models.JSONField(help_text='Prediction output data (JSON)')),
                ('confidence_score', models.DecimalField(decimal_places=4, help_text='Model confidence (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('actual_outcome', models.JSONField(blank=True, help_text='Actual outcome for comparison (JSON)', null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, help_text='Prediction accuracy (0-1)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('feedback_recorded_at', models.DateTimeField(blank=True, help_text='When feedback was recorded', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional prediction metadata')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai.mlmodel')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.node')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='core.train')),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'is_active'], name='ai_mlmodel_model_t_76e995_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['version'], name='ai_mlmodel_version_8e0748_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['trained_at'], name='ai_mlmodel_trained_13f9fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('model_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['prediction_time'], name='ai_predicti_predict_f4aa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['target_time'], name='ai_predicti_target__636965_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['node', 'target_time'], name='ai_predicti_node_id_c48a50_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['train', 'target_time'], name='ai_predicti_train_i_11fd20_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['model', 'prediction_time'], name='ai_predicti_model_i_3c78a7_idx'),
        ),
    ]
