# Generated by Django 5.2.9 on 2026-02-24 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railway_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0, help_text='Current speed in km/h', max_digits=5)),
                ('status', models.CharField(choices=[('MOVING', 'Moving'), ('STOPPED', 'Stopped'), ('BOARDING', 'Boarding'), ('MAINTENANCE', 'Maintenance')], default='STOPPED', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tracking data')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_trains', to='railway_core.node')),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trains', to='railway_core.track')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='railway_core.train')),
            ],
            options={
                'verbose_name': 'Train Position',
                'verbose_name_plural': 'Train Positions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='railway_twi_timesta_9076b5_idx'), models.Index(fields=['train', 'timestamp'], name='railway_twi_train_i_0ea5ed_idx'), models.Index(fields=['current_node', 'timestamp'], name='railway_twi_current_2182ae_idx'), models.Index(fields=['status'], name='railway_twi_status_12ed61_idx')],
            },
        ),
    ]
