# Generated by Django 5.2.9 on 2026-02-24 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('CONGESTION', 'Congestion Alert'), ('DELAY', 'Delay Alert'), ('INCIDENT', 'Incident Alert'), ('ANOMALY', 'Anomaly Detected'), ('MAINTENANCE', 'Maintenance Required'), ('PREDICTION', 'Prediction Alert'), ('SYSTEM', 'System Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional alert data (JSON)')),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_notes', models.TextField(blank=True)),
                ('auto_dismiss_at', models.DateTimeField(blank=True, help_text='Automatically dismiss alert at this time', null=True)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.incident')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.node')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.train')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='analytics_a_alert_t_0b7cc9_idx'), models.Index(fields=['is_acknowledged'], name='analytics_a_is_ackn_2e9bb5_idx'), models.Index(fields=['is_dismissed'], name='analytics_a_is_dism_e18678_idx'), models.Index(fields=['node', 'created_at'], name='analytics_a_node_id_6061c2_idx'), models.Index(fields=['created_at'], name='analytics_a_created_bddfb8_idx')],
            },
        ),
    ]
